name: Deploy GitHub Pages
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch any Git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build docker image
        run: docker build -t pandoc-revealjs-local .devcontainer/
      - name: Build
        run: docker run --rm -v ${PWD}:/workspace -w /workspace pandoc-revealjs-local /bin/bash -c "make dependencies && make build"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you’re changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          force_orphan: true
